### ISSUE TITLE
How do I use a custom Minecraft Forge version?

### ISSUE THREAD

**Issue by UntouchedWagons** [dockhippie/minecraft-forge#11]
I'm trying to figure out how to use this docker container mainly through shotgun debugging. For the mod pack I want to run I have to use Forge version 14.23.3.2679 which I've passed through as FORGE_VERSION and I pointed `/minecraft` to `/mnt/user/appdata/minecraft` but the server never starts:

	> copy template dirs
	find: /minecraft/template: No such file or directory
	> copy template files
	find: /minecraft/template: No such file or directory
	> copy server properties
	cp: can't stat '/minecraft/merge/server.properties': No such file or directory
	> writing motd message
	sed: /minecraft/server.properties: No such file or directory
	> writing rcon password
	sed: /minecraft/server.properties: No such file or directory
	> disabling dynmap mod
	> starting minecraft service
	Error: Unable to access jarfile forge-1.12.2-14.23.2.2629-universal.jar

**Comment by tboerger** [comment]
This image is not built for any dynamic forge version, the env variable just defines the forge version that have been downloaded and built.
