### ISSUE TITLE
Newest version?

### ISSUE THREAD

**Issue by MichalMichalak** [dockhippie/minecraft-forge#15]
Do you have plans to update the versions? Thanks.

**Comment by tboerger** [comment]
I would like to for sure, but first I need to check if I will change the base image as Forge can'T be downloaded with the current JVM, it always fails with some checksum error. The Forge maintainers said it's related to the JVM, they only support Adopt OpenJDK or other Java implementations, this image is using Alpine Linux where you won't find packages for these implementations.

**Comment by tboerger** [comment]
https://github.com/dockhippie/minecraft-forge/pull/16 introduced most recent versions of Forge, but instead of Alpine Linux it's based on Ubuntu because of AdoptOpenJDK now.
