### ISSUE TITLE
Error when trying to run the  latest version of Forge (v39.0.79), Minecraft(v1.18.1) and minecraft-forge docker image

### ISSUE THREAD

**Issue by willcode4food** [dockhippie/minecraft-forge#287]
Hello,

I found this docker project on docker hub and found it to be a great fit for quickly spinning up a Minecraft Forge server with the flexibility to customize it.  Thank you for creating it.  I noticed that the latest version of the docker image runs Minecraft v1.17.1 with Forge Server v37.0.42.  I wanted to run a docker container that supports the latest version of the servers (Forge: v39.0.79, Minecraft: v1.18.1).  I tried using the latest minecraft-forge docker image  and inject environment variables to enable the versions.  

Here is the command I am using

```bash
alias docker-minecraft-forge="docker run --detach --hostname minecraft --publish 25565:25565 --publish 25575:25575 --publish 8123:8123 --name home_minecraft_forge --env MINECRAFT_VERSION='1.18.1' --env MINECRAFT_JAR='minecraft_server.1.18.1.jar' --env FORGE_URL='https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.1-39.0.79/forge-1.18.1-39.0.79-installer.jar' --env FORGE_VERSION='39.0.79' --restart always --volume /Volumes/opt/Games/Containers/minecraft-forge/volume/override:/etc/minecraft/override --volume /Volumes/opt/Games/Containers/minecraft-forge/volume/logs:/var/log/minecraft-forge --volume /Volumes/opt/Games/Containers/minecraft-forge/volume/lib:/var/lib/minecraft webhippie/minecraft-forge:latest"
```

For brevity here are the env vars in a list
```
MINECRAFT_VERSION='1.18.1' 
MINECRAFT_JAR='minecraft_server.1.18.1.jar' 
FORGE_URL='https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.1-39.0.79/forge-1.18.1-39.0.79-installer.jar' 
FORGE_VERSION='39.0.79'
```

When I execute the command i get the following error:  

`Error: could not open libraries/net/minecraftforge/forge/1.18.1-39.0.79/unix_args.txt`

Is what I am attempting to do something this project supports?  If so, I verified that the installer jar, `forge-1.18.1-39.0.79-installer.jar` can successfully be downloaded and can be used to install the server.  The jar for Minecraft v1.18.1 is also available for download.    I'd very much like to use this image if possible with the latest version of the servers.  So any help you could provide would be much appreciated.

Thanks

**Comment by tboerger** [comment]
So far it's not supported to change the version on the fly. The defined environment variables indeed are only used within the Dockerfile to download the required files: https://github.com/dockhippie/minecraft-forge/blob/master/v37.0/Dockerfile.amd64#L13-L17

**Comment by tboerger** [comment]
I have created https://github.com/dockhippie/minecraft-forge/pull/288 now, but this depends on the minecraft-vanilla PR.

**Comment by tboerger** [comment]
I have merged all PRs, so there SHOULD be a new image available pretty soon.

**Comment by willcode4food** [comment]
sounds good. Thanks for responding.

**Comment by tboerger** [comment]
All minor versions up to 39.0 have been built, so I will close this issue.
