### ISSUE TITLE
This docker image looks promising. BUT..

### ISSUE THREAD

**Issue by tkbstudios** [dockhippie/minecraft-forge#336]
# Promising but very buggy
The override files don't override.  
The custom properties aren't loaded (saved to override and main folder)  
We hope the developers of this image actively fix the bugs.  
## Meanwhile
We'll use [itzg's docker MC server](https://github.com/itzg/docker-minecraft-server)  
As soon as everything works, We'll use this docker image.

**Comment by tboerger** [comment]
Can you explain what you tried to do?

**Comment by tkbstudios** [comment]
Simply setup a forge server with custom server.properties and mods

**Comment by tkbstudios** [comment]
Thanks!
