### ISSUE TITLE
tag for 11.15.1

### ISSUE THREAD

**Issue by lasercar** [dockhippie/minecraft-forge#9]
Hello, I am wondering if you can add a tag for the 1.8.9 recommended version of Forge: `11.15.1.1722`? That would be much appreciated!

**Comment by tboerger** [comment]
Solved via https://github.com/dockhippie/minecraft-forge/commit/a72a397f680d24f882b8fada955fa5c63ec60932 but be aware that this will get updated at some point in time with a newer version of 11.15.1.x :)
